source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
inhibit_all_warnings!
platform :ios, '13.0'

target 'Example' do

  # public
  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'SwifterSwift'
  
  # private
  pod 'TAppBase',     :path => '~/Desktop/SourceControl/tang4595/TAppBase' #todo: 同步迁移到github
  pod 'TUtilExt',     :path => '~/Desktop/SourceControl/tang4595/TUtilExt' #todo: 同步迁移到github
  pod 'TNetHttp',     :path => '~/Desktop/SourceControl/tang4595/TNetHttp' #todo: 同步迁移到github
  pod 'TMLViewModel', :git => 'https://github.com/tang4595/TMLViewModel'   #todo: 同步迁移到github
  
  # local
  pod 'KSSCrash', :path => 'Library/KSSCrash'
  
  # debug
  pod 'KSCrash', :git => "https://github.com/tang4595/KSCrash.git", :configurations => ['Debug']
  pod 'LookinServer', :configurations => ['Debug']

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] == '8.0'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end
