source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
inhibit_all_warnings!
platform :ios, '13.0'

target 'Example' do

  # public
  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'SwifterSwift'
  
  # private
  pod 'TAppBase',     :path => '~/Desktop/SourceControl/tang4595/TAppBase'
  pod 'TUtilExt',     :path => '~/Desktop/SourceControl/tang4595/TUtilExt'
  pod 'TNetHttp',     :path => '~/Desktop/SourceControl/tang4595/TNetHttp'
  pod 'TMLViewModel', :git =>  'https://github.com/tang4595/TMLViewModel'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] == '8.0'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end
